// scripts/e2e_localnet.ts — end-to-end CLARO flow against a running dev server
// on surfpool localnet: register → wallet → link → REAL paid checkout → sync →
// report → worker-signed anchor → public verification page.
//
// This is the automated equivalent of the 7-beat demo runbook. Real txs, real
// classification, real anchoring. Requires: surfpool running + .env.local
// generated by setup_devnet.ts + `npm run dev` on :3000.
//
// Usage: SOLANA_RPC_URL=http://localhost:8899 SOLANA_WS_URL=ws://localhost:8900 \
//        npx tsx scripts/e2e_localnet.ts

import {
  appendTransactionMessageInstructions,
  assertIsTransactionWithBlockhashLifetime,
  createSolanaRpc,
  createSolanaRpcSubscriptions,
  createTransactionMessage,
  generateKeyPairSigner,
  getSignatureFromTransaction,
  pipe,
  sendAndConfirmTransactionFactory,
  setTransactionMessageFeePayerSigner,
  setTransactionMessageLifetimeUsingBlockhash,
  signTransactionMessageWithSigners,
} from "@solana/kit";
import { getAddMemoInstruction } from "@solana-program/memo";

const BASE = process.env.E2E_BASE_URL ?? "http://localhost:3000";
const RPC_URL = process.env.SOLANA_RPC_URL ?? "http://localhost:8899";
const WS_URL = process.env.SOLANA_WS_URL ?? "ws://localhost:8900";

const rpc = createSolanaRpc(RPC_URL);
const rpcSubscriptions = createSolanaRpcSubscriptions(WS_URL);
const sendAndConfirm = sendAndConfirmTransactionFactory({ rpc, rpcSubscriptions });

async function sendAndConfirmPolling(signedTx: Parameters<typeof sendAndConfirm>[0]) {
  const signature = getSignatureFromTransaction(signedTx);
  try {
    await sendAndConfirm(signedTx, { commitment: "confirmed" });
    return signature;
  } catch {
    const deadline = Date.now() + 60_000;
    while (Date.now() < deadline) {
      const { value } = await rpc.getSignatureStatuses([signature]).send();
      const st = value[0];
      if (st) {
        if (st.err) throw new Error(`tx failed: ${JSON.stringify(st.err)}`);
        if (st.confirmationStatus === "confirmed" || st.confirmationStatus === "finalized") return signature;
      }
      await new Promise((r) => setTimeout(r, 1500));
    }
    throw new Error("confirmation timeout");
  }
}

let cookie = "";
async function api(path: string, init?: RequestInit) {
  const res = await fetch(`${BASE}${path}`, {
    ...init,
    headers: {
      "Content-Type": "application/json",
      ...(cookie ? { cookie } : {}),
      ...(init?.headers ?? {}),
    },
  });
  const setCookie = res.headers.get("set-cookie");
  if (setCookie) cookie = setCookie.split(";")[0];
  const text = await res.text();
  let json: unknown = null;
  try { json = JSON.parse(text); } catch { /* html pages */ }
  return { status: res.status, json, text };
}

function check(cond: boolean, label: string, detail?: unknown) {
  if (!cond) {
    console.error(`  FAIL ${label}`, detail ?? "");
    process.exit(1);
  }
  console.log(`  ok ${label}`);
}

async function main() {
  console.log(`CLARO E2E — ${BASE} (rpc ${RPC_URL})`);

  // Beat 1 — register: worker keypair client-side equivalent.
  const worker = await generateKeyPairSigner(true);
  console.log(`worker: ${worker.address}`);
  let r = await api("/api/session", {
    method: "POST",
    body: JSON.stringify({ email: "e2e@claro.test" }),
  });
  check(r.status === 200 && !!cookie, "session + cookie", r.status);
  r = await api("/api/user/wallet", {
    method: "POST",
    body: JSON.stringify({ wallet: worker.address }),
  });
  check(r.status === 200, "wallet registered (pubkey only — CA-1)", r.status);

  // Beat 2 — payment link with unique reference.
  r = await api("/api/links", {
    method: "POST",
    body: JSON.stringify({ amountMicro: "250000000", memo: "Diseño web — entrega final" }),
  });
  check(r.status === 200, "link created", r.text);
  const { slug, reference } = (r.json as { link: { slug: string; reference: string } }).link;
  console.log(`  link: /pagar/${slug}  ref: ${reference}`);

  // Beat 3 — public checkout page + REAL payment (2 payers, repeated on same link).
  r = await api(`/pagar/${slug}`);
  check(r.status === 200 && r.text.includes("250"), "public checkout renders", r.status);
  const sig1 = await api("/api/checkout/pay", {
    method: "POST",
    body: JSON.stringify({ slug }),
  });
  check(sig1.status === 200, "checkout payment 1 confirmed onchain", sig1.text);
  const sig2 = await api("/api/checkout/pay", {
    method: "POST",
    body: JSON.stringify({ slug }),
  });
  check(sig2.status === 200, "checkout payment 2 (repeat, other payer)", sig2.text);
  const s1 = (sig1.json as { signature: string }).signature;
  const s2 = (sig2.json as { signature: string }).signature;
  check(s1 !== s2, "two distinct signatures", `${s1} ${s2}`);
  console.log(`  tx1: ${s1}\n  tx2: ${s2}`);

  // Beat 4 — history sync classifies from chain.
  r = await api("/api/history/sync", { method: "POST" });
  check(r.status === 200, "history sync", r.text);
  console.log(`  sync: ${r.text}`);

  // Beat 6 — report creation + worker-signed anchor.
  r = await api("/api/reports", {
    method: "POST",
    body: JSON.stringify({ periodMonths: 1, includeEvidence: true, ttlDays: 30 }),
  });
  check(r.status === 200, "report created", r.text);
  const report = (r.json as { report: { slug: string; hash: string } }).report;
  console.log(`  report: /verificar/${report.slug}  hash: ${report.hash}`);

  // fee grant then worker-signed memo anchor (client-side equivalent of lib/anchor.ts)
  r = await api("/api/reports/anchor-fee", {
    method: "POST",
    body: JSON.stringify({ worker: worker.address }),
  });
  check(r.status === 200, "anchor fee grant", r.text);

  const { value: latestBlockhash } = await rpc.getLatestBlockhash().send();
  const memo = `CLARO-RPT:v1:${report.hash}`;
  const message = pipe(
    createTransactionMessage({ version: 0 }),
    (m) => setTransactionMessageFeePayerSigner(worker, m),
    (m) => setTransactionMessageLifetimeUsingBlockhash(latestBlockhash, m),
    (m) =>
      appendTransactionMessageInstructions(
        [getAddMemoInstruction({ memo, signers: [worker] })],
        m
      )
  );
  const signedTx = await signTransactionMessageWithSigners(message);
  assertIsTransactionWithBlockhashLifetime(signedTx);
  const anchorSig = await sendAndConfirmPolling(signedTx);
  console.log(`  anchor tx (worker-signed): ${anchorSig}`);

  r = await api(`/api/reports/${report.slug}/anchor`, {
    method: "POST",
    body: JSON.stringify({ signature: anchorSig }),
  });
  check(r.status === 200, "anchor verified + registered", r.text);

  // Beat 7 — public verification page renders checks.
  r = await api(`/verificar/${report.slug}`);
  check(r.status === 200, "public verification page", r.status);
  const checks = ["hash", "verificad", "ancl"];
  for (const c of checks) {
    check(r.text.toLowerCase().includes(c), `page mentions "${c}"`);
  }

  console.log("\nE2E COMPLETE — all beats verified with real transactions.");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
